import dotenv from "dotenv";
dotenv.config();

export const badWords = [
  "Anjing",
  "iclik",
  "babi",
  "memek",
  "kontol",
  "ANJING",
  "4NJING",
  "4nj",
];

export const responses = [
  "Jaga bicara, ya!",
  "Kata-kata seperti itu tidak baik.",
  "Ayo bicara dengan sopan.",
  "Kurangi kata kasar, ok?",
];

export const commandsBot = `
**Daftar Perintah yang Didukung oleh Bot:**

1. **Hallo sep**: Balasan: 'Hallo Juga bang'
2. **sepi banget nih sep**: Balasan: 'iya nih bang pada kemana ya?'
3. **p login**: Balasan: 'Gass ken bang gua juga login nih(dalam mimpi)'
4. **iclik**: Balasan: 'Dilarang berkata kasar, karena admin melihat'
5. **halo**: Balasan: 'halo juga'
6. **ingpokan le**: Balasan: 'ingpokan juga bang belajar coding bareng'
7. **hallo**: Balasan: 'hallo juga, salam kenal gua asep. bot paling ramah disini'
8. **ingpo mint**: Balasan: 'admint sedang turu, biar gua saja yang menggantikannya'
9. **ayo coding guys**: Balasan: 'ayo bang gua juga mau ikut'
10. **asep pake bahasa pemograman apa?**: Balasan: 'mau tau apa mau tau banget nih bang???. malas ah kasih taunya'
11. **asep on 24jam kah?**: Balasan: 'ya enggak dong, orang pc yang buat asep aja gak 24 jam nyala bagaimana asep mau nyala'
12. **p**: Balasan: 'singkat sekali.p'
13. **cek role @user**: Menampilkan role pengguna yang ditandai
14. **cek gambar <URL>**: Menampilkan gambar dari URL yang diberikan
15. **cek perintah**: Menampilkan daftar perintah yang didukung oleh bot
`;

export const balesPesan = [
  {
    pesan: "Hallo sep",
    balesan: "hallo juga bang",
  },
  {
    pesan: "sepi banget nih sep",
    balesan: "iya nih bang pada kemana ya?",
  },
  {
    pesan: "p login",
    balesan: "gass ken bang gua juga login nih(dalam mimpi)",
  },
  {
    pesan: "halo",
    balesan: "halo juga",
  },
  {
    pesan: "ingpokan le",
    balesan: "ingpokan juga bang belajar coding bareng",
  },
  {
    pesan: "hallo",
    balesan: "hallo juga, salam kenal gua asep. bot paling ramah disini",
  },
  {
    pesan: "ingpo mint",
    balesan: "admint sedang turu, biar gua saja yang menggantikannya",
  },
  {
    pesan: "ayo coding guys",
    balesan: "ayo bang gua juga mau ikut",
  },
  {
    pesan: "asep pake bahasa pemograman apa?",
    balesan: "mau tau apa mau tau banget nih bang???. malas ah kasih taunya",
  },
  {
    pesan: "asep on 24jam kah?",
    balesan:
      "ya enggak dong, orang pc yang buat asep aja gak 24 jam nyala bagaimana asep mau nyala",
  },
  {
    pesan: "p",
    balesan: "singkat sekali p doang",
  },
];
export const config = {
  token: process.env.TOKEN_DISCORD,
  clientID: process.env.CLIENT_ID,
  guildID: process.env.GUILD_ID,
};
const nameLanguage = {
  afar: "aa",
  abkhazian: "ab",
  afrikaans: "af",
  akan: "ak",
  albanian: "sq",
  amharic: "am",
  arabic: "ar",
  aragonese: "an",
  armenian: "hy",
  assamese: "as",
  avaric: "av",
  avestan: "ae",
  aymara: "ay",
  azerbaijani: "az",
  bashkir: "ba",
  bambara: "bm",
  basque: "eu",
  belarusian: "be",
  bengali: "bn",
  "bihari languages": "bh",
  bislama: "bi",
  tibetan: "bo",
  bosnian: "bs",
  breton: "br",
  bulgarian: "bg",
  burmese: "my",
  catalan: "ca",
  valencian: "ca",
  czech: "cs",
  chamorro: "ch",
  chechen: "ce",
  chinese: "zh",
  "church slavic": "cu",
  "old slavonic": "cu",
  "church slavonic": "cu",
  "old bulgarian": "cu",
  "old church slavonic": "cu",
  chuvash: "cv",
  cornish: "kw",
  corsican: "co",
  cree: "cr",
  welsh: "cy",
  danish: "da",
  german: "de",
  divehi: "dv",
  dhivehi: "dv",
  maldivian: "dv",
  dutch: "nl",
  flemish: "nl",
  dzongkha: "dz",
  greek: "el",
  english: "en",
  esperanto: "eo",
  estonian: "et",
  ewe: "ee",
  faroese: "fo",
  persian: "fa",
  fijian: "fj",
  finnish: "fi",
  french: "fr",
  "western frisian": "fy",
  fulah: "ff",
  georgian: "ka",
  gaelic: "gd",
  "scottish gaelic": "gd",
  irish: "ga",
  galician: "gl",
  manx: "gv",
  guarani: "gn",
  gujarati: "gu",
  haitian: "ht",
  "haitian creole": "ht",
  hausa: "ha",
  hebrew: "he",
  herero: "hz",
  hindi: "hi",
  "hiri motu": "ho",
  croatian: "hr",
  hungarian: "hu",
  igbo: "ig",
  icelandic: "is",
  ido: "io",
  "sichuan yi": "ii",
  nuosu: "ii",
  inuktitut: "iu",
  interlingue: "ie",
  occidental: "ie",
  interlingua: "ia",
  indonesian: "id",
  inupiaq: "ik",
  italian: "it",
  javanese: "jv",
  japanese: "ja",
  kalaallisut: "kl",
  greenlandic: "kl",
  kannada: "kn",
  kashmiri: "ks",
  kanuri: "kr",
  kazakh: "kk",
  "central khmer": "km",
  kikuyu: "ki",
  gikuyu: "ki",
  kinyarwanda: "rw",
  kirghiz: "ky",
  kyrgyz: "ky",
  komi: "kv",
  kongo: "kg",
  korean: "ko",
  kuanyama: "kj",
  kwanyama: "kj",
  kurdish: "ku",
  lao: "lo",
  latin: "la",
  latvian: "lv",
  limburgan: "li",
  limburger: "li",
  limburgish: "li",
  lingala: "ln",
  lithuanian: "lt",
  luxembourgish: "lb",
  letzeburgesch: "lb",
  "luba-katanga": "lu",
  ganda: "lg",
  macedonian: "mk",
  marshallese: "mh",
  malayalam: "ml",
  maori: "mi",
  marathi: "mr",
  malay: "ms",
  malagasy: "mg",
  maltese: "mt",
  mongolian: "mn",
  nauru: "na",
  navajo: "nv",
  navaho: "nv",
  "ndebele, south": "nr",
  "south ndebele": "nr",
  "ndebele, north": "nd",
  "north ndebele": "nd",
  ndonga: "ng",
  nepali: "ne",
  "norwegian nynorsk": "nn",
  "nynorsk, norwegian": "nn",
  "norwegian bokmål": "nb",
  "bokmål, norwegian": "nb",
  norwegian: "no",
  chichewa: "ny",
  chewa: "ny",
  nyanja: "ny",
  occitan: "oc",
  ojibwa: "oj",
  oriya: "or",
  oromo: "om",
  ossetian: "os",
  ossetic: "os",
  panjabi: "pa",
  punjabi: "pa",
  pali: "pi",
  polish: "pl",
  portuguese: "pt",
  pushto: "ps",
  pashto: "ps",
  quechua: "qu",
  romansh: "rm",
  romanian: "ro",
  moldavian: "ro",
  moldovan: "ro",
  rundi: "rn",
  russian: "ru",
  sango: "sg",
  sanskrit: "sa",
  sinhala: "si",
  sinhalese: "si",
  slovak: "sk",
  slovenian: "sl",
  "northern sami": "se",
  samoan: "sm",
  shona: "sn",
  sindhi: "sd",
  somali: "so",
  "sotho, southern": "st",
  spanish: "es",
  castilian: "es",
  sardinian: "sc",
  serbian: "sr",
  swati: "ss",
  sundanese: "su",
  swahili: "sw",
  swedish: "sv",
  tahitian: "ty",
  tamil: "ta",
  tatar: "tt",
  telugu: "te",
  tajik: "tg",
  tagalog: "tl",
  thai: "th",
  tigrinya: "ti",
  tonga: "to",
  tswana: "tn",
  tsonga: "ts",
  turkmen: "tk",
  turkish: "tr",
  twi: "tw",
  uighur: "ug",
  uyghur: "ug",
  ukrainian: "uk",
  urdu: "ur",
  uzbek: "uz",
  venda: "ve",
  vietnamese: "vi",
  volapük: "vo",
  walloon: "wa",
  wolof: "wo",
  xhosa: "xh",
  yiddish: "yi",
  yoruba: "yo",
  zhuang: "za",
  chuang: "za",
  zulu: "zu",
};

const listBahasa = [];
for (const [nama, iso] of Object.entries(nameLanguage)) {
  listBahasa.push({
    name: nama,
    value: iso,
  });
}
export { listBahasa };
